export const countries = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Sweden",
  "Norway",
  "Finland",
  "Denmark",
  "Switzerland",
  "Japan",
  "China",
  "South Korea",
  "Singapore",
  "United Arab Emirates",
  "Saudi Arabia",
  "Brazil",
  "Argentina",
  "Mexico",
  "South Africa",
];